### ISSUE TITLE
Rust layer replies with error to sent transaction memo query 

### ISSUE THREAD

**Issue by HonzaR** [zcash/zcash-android-wallet-sdk#1154]
### Describe the issue
Rust layer replies with an error to the sent transaction memo query.

#### If so, please list the steps to reproduce below:
1. Run Demo-app
2. Select one of the predefined wallets (Alice/Ben: both have sapling funds available)
3. Let it sync
4. Hit Send and send some sapling funds to the opposite sapling address
5. Fill in the Memo field
6. Hit Send button and wait for confirmation
7. Then go to the Transaction screen
8. And hit any displayed sent transaction to query its memo - the memo should then be printed into the console

### Expected behaviour
The same as for received transactions. It replies with an empty string/error in case of no memo in the transaction and with a valid string memo in case of a transaction with a memo.

### Actual behavior + errors
```
java.lang.RuntimeException: An error occurred retrieving the memo, Query returned no rows
```

### Any extra information that might be useful in the debugging process.
Reported in https://github.com/zcash/librustzcash/issues/834.

**Comment by nuttycom** [comment]
The issue appears to be that the Android SDK is attempting to use the transaction ID as the note identifier for calling `get_memo` in the Rust backend: https://github.com/zcash/zcash-android-wallet-sdk/blob/1a0508f57dfa6eec68668f4705990f59f62ff3c5/sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/TxOutputsView.kt#L38-L50

The note ID is not currently returned from the `v_tx_outputs` view. We can either change that, or the memos can be retrieved directly from that view rather than making an extra `get_memo` call.

**Comment by HonzaR** [comment]
Closing as resolved by this [commit](https://github.com/zcash/zcash-android-wallet-sdk/pull/1116/commits/ae833533c1baefb38579856cb6cf6750b3a1d528).
