### ISSUE TITLE
Integrate test suite with darksidewalletd

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-android-wallet-sdk#127]
Incorporate darksidewalletd into SDK testing suite.

Criteria: 
- [ ] Able to access darksidewalletd APIs from tests

**Comment by braddmiller** [comment]
This has been replaced by #125 and #126

**Comment by gmale** [comment]
Encountered issues with expected hashes, as it relates to checkpoints. In a nutshell, the darkside APIs create synthetic blocks but our code works with checkpoints based on production blocks. So we needed to bridge the gap.

In the future, we can create testing checkpoints that have the synthetic hash rather than the production hash. For now, @LarryRuane was nice enough to update the test data set to use a production hash for the first block!

Integration is now working and the sanity test is passing. This ticket can be moved into review.

![Screenshot from 2020-05-20 18-08-29.png](https://images.zenhubusercontent.com/5dc318c2f708b700019dbee0/40528216-e1a0-449d-a6e7-a418274509a5)
