### ISSUE TITLE
Master branch does not compile on Windows

### ISSUE THREAD

**Issue by herou** [zcash/zcash-android-wallet-sdk#222]
**What is the bug?**
When trying to compile master, it shows an error.

![c1](https://user-images.githubusercontent.com/13895430/115986495-bdad2400-a5b0-11eb-95c0-ad7916bf66b0.png)
![c2](https://user-images.githubusercontent.com/13895430/115986498-bede5100-a5b0-11eb-809c-530a3f0fbb29.png)

The bug was introduced on 23/24 aprill and it is happening on Windows 10 OS.
@gmale fix it locally for me.

**Comment by gmale** [comment]
After digging into this, it is an issue with the packaging tool that creates the AAR. For some reason, it includes a file n the META-INF directory with a colon in the file name rather than the version. Apparently, Windows machines cannot handle this but other platforms can. It becomes an issue during the Jetify Transform process as it attempts to modify the library file for compatibility with Androidx.

There are two fixes here:

1) Remove the Jetifier from the project so that neither the SDK nor the Wallet depend on it. Although this doesn't fix the root issue, it is still a good option to pursue.
2) Fix the root issue and ensure that the AAR library file is created with a filename for `META-INF/zcash-android-sdk-[:]_release.kotlin_module` that includes the version instead of a colon.

As a temporary workaround, this file name can be changed inside the AAR file in the local gradle cache.

**Comment by gmale** [comment]
Notes:
- We might be able to explicity set the kotlin module name via [kotlinOptions.freeCompilerArgs](https://stackoverflow.com/a/45235642/178433)
