### ISSUE TITLE
Wallet crashes on startup!

### ISSUE THREAD

**Issue by herou** [zcash/zcash-android-wallet-sdk#223]
On startup, wallet crashes:

![image](https://user-images.githubusercontent.com/13895430/116312868-501a1700-a7ad-11eb-9879-001a21ae1408.png)

**Comment by gmale** [comment]
Is this a fresh build of `master`?
If not, are there changes in `MainActivity`?

Can you give more context on when this happens?
Is it the first run after upgrading a wallet?
Is this a wallet that starts up after falling asleep?
Does it happen every time?

Any details you can provide to help recreate the scenario would help because the wallet generally appears to work for most users.

**Comment by gmale** [comment]
This is most likely a timing issue and requires a cleanup of the `launchWhenSyncing` logic on the wallet. If that's the case, then we can move this issue over to the [proper repo](https://github.com/zcash/zcash-android-wallet/issues) because it is probably an issue with the wallet and not the SDK.

**Comment by herou** [comment]
> Thanks Elio! Can you give more context on when this happens?
> 
> Is this a fresh build of `master`?
> If not, are there changes in `MainActivity`?
> 
> Is it the first run after upgrading a wallet?
> Is this a wallet that starts up after falling asleep?
> Does it happen every time?
> 
> Any details you can provide to help recreate the scenario would help because the wallet generally appears to work for most users (so I suspect that this is specific to a particular device or a certain workflow).

It is fresh install, no changes.

**Comment by herou** [comment]
@gmale , please merge this with master because master keeps crashing.
