### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by defuse** [zcash/zcash-android-wallet-sdk#24]
https://github.com/zcash/zcash-android-wallet-sdk/blob/preview/docs/-synchronizer/balance.md

Clicking `Wallet.WalletBalance` 404's, I think it should go to https://github.com/zcash/zcash-android-wallet-sdk/blob/preview/docs/-wallet/-wallet-balance/README.md.

**Comment by gmale** [comment]
Noted.
There is a documentation task that changes all `index.md` file names to `README.md` so that they behave better on Github. Scanning all the documentation and updating links is out of scope.

The current documentation is a stop-gap intended to provide some initial guidance but not intended as a permanent solution. Ultimately, we do not want to host API documentation (e.g. KDocs) inside the actual repository. Instead, we'll host that static content elsewhere.

**Comment by gmale** [comment]
Closing since this will automatically resolve itself once the API docs are migrated to their permanent home. Right now, this repo is in a "developer preview" status so it's okay if things like this are not finalized.
