### ISSUE TITLE
Missing Steps in README

### ISSUE THREAD

**Issue by defuse** [zcash/zcash-android-wallet-sdk#331]
- [ ] The readme does not say to set the JAVA_HOME environment variable (which is necessary for the CLI build)
- [ ] It's missing `x86_64-linux-android` from the `rustup target add...` command.
- [ ] There's an outdated reference to `Deps.kt` in the README (this file does not seem to exist anymore)

**Comment by ccjernigan** [comment]
Cross-platform code always breaks once we actually test it on different platforms.  JAVA_HOME is not usually explicitly needed on macOS, but I think it is on Linux and maybe Windows so that's a good addition.

I see `x86_64-linux-android` in the readme now and I don't see mention of Deps.kt.  Could you be looking at the beta release branch instead of master?

**Comment by ccjernigan** [comment]
After a few recent changes, these should all be resolved now on the master branch.
