### ISSUE TITLE
ECC wallet fails to scan blocks: "database disk image is malformed"

### ISSUE THREAD

**Issue by pacu** [zcash/zcash-android-wallet-sdk#344]
![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/83132892-f698-4cad-894b-ffaa8b6413e6)

**cause:**
 java.lang.RuntimeException: Rust error while scanning block batch: database disk image is malformed

**description**
Error: non-fatal reported error due to: cash.z.ecc.android.sdk.exception.CompactBlockProcessorException$FailedScan: Error while scanning blocks. This most likely means a block was missed or a reorg was mishandled. See logs for details.

**More bugsnag details**
````
exceptionString
cash.z.ecc.android.sdk.exception.CompactBlockProcessorException$FailedScan: Error while scanning blocks. This most likely means a block was missed or a reorg was mishandled. See logs for details.

isError
true

isFatal
false

key
error.nonfatal.reported

message
Error while scanning blocks. This most likely means a block was missed or a reorg was mishandled. See logs for details.

stacktrace.0
cash.z.ecc.android.sdk.exception.CompactBlockProcessorException$FailedScan: Error while scanning blocks. This most likely means a block was missed or a reorg was mishandled. See logs for details.
	at cash.z.ecc.android.sdk.block.CompactBlockProcessor

stacktrace.1
$scanNewBlocks$2.invokeSuspend(CompactBlockProcessor.kt:539)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling

stacktrace.2
.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:67

stacktrace.3
8)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.RuntimeException: Rust error while scanning block batch: database disk image is malformed
	at cash.z.ecc.android.sdk.jni.RustBackend.sc

stacktrace.4
anBlockBatch(Native Method)
	at cash.z.ecc.android.sdk.jni.RustBackend.access$scanBlockBatch(RustBackend.kt:18)
	at cash.z.ecc.android.sdk.jni.RustBackend$Companion.scanBlockBatch(Unknown Source:0)
	at cash.z.ecc.android.sdk.jni.RustBackend$Companion

stacktrace.5
.access$scanBlockBatch(RustBackend.kt:205)
	at cash.z.ecc.android.sdk.jni.RustBackend.scanBlocks(RustBackend.kt:111)
	at cash.z.ecc.android.sdk.block.CompactBlockProcessor$scanNewBlocks$2.invokeSuspend(CompactBlockProcessor.kt:544)
	... 6 more
````

Device status: 
- Free memory available
- Free disk space available

**Comment by ccjernigan** [comment]
I think we have several different mitigation steps that will help resolve this:
 - Identify the underlying root cause of the database corruption
 - Improve the SDK's error API to make it more clear what's the problem.  Currently, the SDK thinks the issue is an application logic issue with the data and that something like a rescan might fix it.  But actually the sqlite database itself is corrupted.  Fixing this might require enhancements at the Rust layer to better signal the type of error that occurred.
 - Improve the error screen so that the app's built-in troubleshooting steps are accessible (e.g. rescan, wipe).  While the screenshot is from the old wallet app, we're planning to add an improved error handing screen to the Secant wallet app described here https://github.com/zcash/secant-android-wallet/issues/175

I plan to use this issue to track the first item (identifying the underlying root cause of database corruption)
